### ISSUE TITLE
Not able to use the plugin

### ISSUE THREAD

**Issue by jaikishore08** [perrydevx/simple-sftp#1]
Could not find org.grails.plugins:simple-sftp:0.3.
     Searched in the following locations:
        https://repo.grails.org/grails/core/org/grails/plugins/simple-sftp/0.3/simple-sftp-0.3.pom
         https://repo.grails.org/grails/core/org/grails/plugins/simple-sftp/0.3/simple-sftp-0.3.jar

**Comment by perrydevx** [comment]
Plugin hasn't been updated for Grails 3.
you can find it in old repo
http://repo.grails.org/grails/plugins/org/grails/plugins/simple-sftp/
